# Generated by Django 3.2.8 on 2022-09-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_logos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logos',
            name='imagenlogo',
        ),
        migrations.AddField(
            model_name='logos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Logo'),
        ),
    ]
