# Generated by Django 3.2.8 on 2022-09-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20220929_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/logo', verbose_name='Logo'),
        ),
    ]
