# Generated by Django 3.2.8 on 2022-09-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_logos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/logo'),
        ),
    ]
